### ISSUE TITLE
Using language keywords should cause a yaml exception

### ISSUE THREAD

**Issue by kmccoan-allocadia** [kormide/recipe#50]
*Steps to Reproduce*
* In a parameter use a language keyword. For example, `public` when generating java setups or one of the ones from https://github.com/Microsoft/TypeScript/issues/2536 if generating typescript setups
```
- name: Example
    required:
      - name: public
        type: string
    initializers:
      - params: ["public"]
```

*Expected*
A generation failure with the line/column number pointing to the yaml so its easy to figure out which param is incorrect and why

*Actual*
A compilation failure in the generated code
